commonLabels:
  org: lsst
  app: qserv
  tier: ingest

resources:
- init.yaml

secretGenerator:
- name: repl-creds 
  files:
  - qserv 
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

configMapGenerator:
- name: config-data-url
  literals:
  - DATA_URL="https://raw.githubusercontent.com/lsst-dm/qserv-DC2/tickets/DM-24587/data/example_db/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

